name: Continuous Deployment

on:
  push:
    branches:
      - main # Imported restrict commits and pushes to main directly, PR only

jobs:
  deploy-to-prod-stage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout prod repository
        uses: actions/checkout@v4
        with:
          path: prod
          ref: prod

      - name: Remove dist from prod
        run: rm -rf prod/dist

      - name: Copy dist from dev to prod stage
        run: cp -r dist prod/

      - name: Commit and push to prod repository
        run: |
          cd prod
          git add -f ./dist
          git config --global user.name "EDS CI/CD"
          git config --global user.email "eds-dev-cd@diva-e.com"
          git add dist
          git commit -m "Deploy dist"
          git push