name: Build
on: # on: [push]
  push:
    branches:
      - '60-dist-folder-should-not-be-pushed' #For testing reasons ony this branch
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: "Continuous Integration Build Project"
      CI_COMMIT_AUTHOR: "${{ github.event.repository.name }} Continuous Integration"

    steps:
      - name: Display event name
        run: echo "github.event_name=${{ github.event_name }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Lint project
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run unit tests
        run: npm run test:ci

      - name: Check if dist directory has changed
        id: check-dist-changes
        run: git diff --quiet HEAD ${{ github.event.before }} -- ./dist || echo "::set-output name=dist_changed::true"

      - name: Commit dist and types if changed
        if: steps.check-dist-changes.outputs.dist_changed == 'true'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "eds-editorial-ci@diva-e.com"
          git add -f ./dist
          git add -f ./types
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push